import os
from typing import Final
import re
GS1_list: Final[dict] = [
    {"000 – 019": "United States and Canada"},
    {"030 – 039": "United States drugs (National Drug Code)"},
    {"060 – 099": "United States and Canada"},
    {"100 – 139": "United States"},
    {"200 – 299": "Restricted distribution"},
    {"300 – 379": "France and Monaco"},
    {"380": "Bulgaria"},
    {"383": "Slovenia"},
    {"385": "Croatia"},
    {"387": "Bosnia and Herzegovina"},
    {"389": "Montenegro"},
    {"400 – 440": "Germany"},
    {"450 – 459": "Japan"},
    {"460 – 469": "Russian Federation"},
    {"470": "Kyrgyzstan"},
    {"471": "Taiwan, Province of China"},
    {"474": "Estonia"},
    {"475": "Latvia"},
    {"476": "Azerbaijan"},
    {"477": "Lithuania"},
    {"478": "Uzbekistan"},
    {"479": "Sri Lanka"},
    {"480": "Philippines"},
    {"481": "Belarus"},
    {"482": "Ukraine"},
    {"484": "Moldova, Republic of"},
    {"485": "Armenia"},
    {"486": "Georgia"},
    {"487": "Kazakhstan"},
    {"488": "Tajikistan"},
    {"489": "Hong Kong"},
    {"490 – 499": "Japan"},
    {"500 – 509": "United Kingdom"},
    {"520 – 521": "Greece"},
    {"528": "Lebanon"},
    {"529": "Cyprus"},
    {"530": "Albania"},
    {"531": "North Macedonia"},
    {"535": "Malta"},
    {"539": "Ireland"},
    {"540 – 549": "Belgium and Luxembourg"},
    {"560": "Portugal"},
    {"569": "Iceland"},
    {"570 – 579": "Denmark and Faroe Islands and Greenland"},
    {"590": "Poland"},
    {"594": "Romania"},
    {"599": "Hungary"},
    {"600 – 601": "South Africa"},
    {"603": "Ghana"},
    {"604": "Senegal"},
    {"608": "Bahrain"},
    {"609": "Mauritius"},
    {"611": "Morocco"},
    {"613": "Algeria"},
    {"615": "Nigeria"},
    {"616": "Kenya"},
    {"618": "Côte d'Ivoire"},
    {"619": "Tunisia"},
    {"621": "Syrian Arab Republic"},
    {"622": "Egypt"},
    {"624": "Libya"},
    {"625": "Jordan"},
    {"626": "Iran, Islamic Republic of"},
    {"627": "Kuwait"},
    {"628": "Saudi Arabia"},
    {"629": "United Arab Emirates"},
    {"640 – 649": "Finland"},
    {"690 – 695": "China"},
    {"700 – 709": "Norway"},
    {"729": "Israel"},
    {"730 – 739": "Sweden"},
    {"740": "Guatemala"},
    {"741": "El Salvador"},
    {"742": "Honduras"},
    {"743": "Nicaragua"},
    {"744": "Costa Rica"},
    {"745": "Panama"},
    {"746": "Dominican Republic"},
    {"750": "Mexico"},
    {"754 – 755": "Canada"},
    {"759": "Venezuela, Bolivarian Republic of"},
    {"760 – 769": "Switzerland and Liechtenstein"},
    {"770 – 771": "Colombia"},
    {"773": "Uruguay"},
    {"775": "Peru"},
    {"777": "Bolivia, Plurinational State of"},
    {"779": "Argentina"},
    {"780": "Chile"},
    {"784": "Paraguay"},
    {"785": "Peru"},
    {"786": "Ecuador"},
    {"789 – 790": "Brazil"},
    {"800 – 839": "Italy and San Marino and Holy See (Vatican City State)"},
    {"840 – 849": "Spain and Andorra"},
    {"850": "Cuba"},
    {"858": "Slovakia"},
    {"859": "Czechia"},
    {"860": "Serbia"},
    {"865": "Mongolia"},
    {"867": "Korea, Democratic People's Republic of"},
    {"868 – 869": "Türkiye"},
    {"870 – 879": "Netherlands"},
    {"880": "Korea, Republic of"},
    {"884": "Cambodia"},
    {"885": "Thailand"},
    {"888": "Singapore"},
    {"890": "India"},
    {"893": "Viet Nam"},
    {"896": "Pakistan"},
    {"899": "Indonesia"},
    {"900 – 919": "Austria"},
    {"930 – 939": "Australia"},
    {"940 – 949": "New Zealand"},
    {"950": "GS1 Global Office: Special applications"},
    {"951": "EPCglobal: Special applications"},
    {"955": "Malaysia"},
    {"958": "Macao"},
    {"960 – 969": "GS1 Global Office: GTIN-8 allocations"},
    {"977": "Serial publications (ISSN)"},
    {"978 – 979": "Bookland (ISBN) – 979 formerly used for sheet music"},
    {"980": "Refund receipts"},
    {"981 – 984": "GS1 coupon identification for common currency areas"},
    {"990 – 999": "Coupon identification"}
]

# Manual mapping of French country names to English
country_fr_to_en: Final[dict] = {
    "afghanistan": "Afghanistan",
    "albanie": "Albania",
    "algérie": "Algeria",
    "andorre": "Andorra",
    "angola": "Angola",
    "antigua-et-barbuda": "Antigua and Barbuda",
    "argentine": "Argentina",
    "arménie": "Armenia",
    "australie": "Australia",
    "autriche": "Austria",
    "azerbaïdjan": "Azerbaijan",
    "bahamas": "Bahamas",
    "bahreïn": "Bahrain",
    "bangladesh": "Bangladesh",
    "barbade": "Barbados",
    "biélorussie": "Belarus",
    "belgique": "Belgium",
    "belize": "Belize",
    "bénin": "Benin",
    "bhoutan": "Bhutan",
    "bolivie": "Bolivia",
    "bosnie-herzégovine": "Bosnia and Herzegovina",
    "botswana": "Botswana",
    "brésil": "Brazil",
    "bresil": "Brazil",
    "brunei": "Brunei",
    "bulgarie": "Bulgaria",
    "burkina faso": "Burkina Faso",
    "burundi": "Burundi",
    "cambodge": "Cambodia",
    "cameroun": "Cameroon",
    "canada": "Canada",
    "cap-vert": "Cape Verde",
    "république centrafricaine": "Central African Republic",
    "tchad": "Chad",
    "chili": "Chile",
    "chine": "China",
    "colombie": "Colombia",
    "comores": "Comoros",
    "congo": "Congo",
    "costa rica": "Costa Rica",
    "croatie": "Croatia",
    "cuba": "Cuba",
    "chypre": "Cyprus",
    "république tchèque": "Czech Republic",
    "danemark": "Denmark",
    "djibouti": "Djibouti",
    "dominique": "Dominica",
    "république dominicaine": "Dominican Republic",
    "équateur": "Ecuador",
    "equateur": "Ecuador",
    "égypte": "Egypt",
    "salvador": "El Salvador",
    "guinée équatoriale": "Equatorial Guinea",
    "érythrée": "Eritrea",
    "estonie": "Estonia",
    "éthiopie": "Ethiopia",
    "fiji": "Fiji",
    "finlande": "Finland",
    "france": "France",
    "gabon": "Gabon",
    "gambie": "Gambia",
    "géorgie": "Georgia",
    "allemagne": "Germany",
    "ghana": "Ghana",
    "grèce": "Greece",
    "grenade": "Grenada",
    "guatemala": "Guatemala",
    "guinée": "Guinea",
    "guinée-bissau": "Guinea-Bissau",
    "guyane": "Guyana",
    "haïti": "Haiti",
    "honduras": "Honduras",
    "hongrie": "Hungary",
    "islande": "Iceland",
    "inde": "India",
    "indonésie": "Indonesia",
    "iran": "Iran",
    "irak": "Iraq",
    "irlande": "Ireland",
    "israël": "Israel",
    "italie": "Italy",
    "jamaïque": "Jamaica",
    "japon": "Japan",
    "jordanie": "Jordan",
    "kazakhstan": "Kazakhstan",
    "kenya": "Kenya",
    "kiribati": "Kiribati",
    "corée du nord": "North Korea",
    "corée du sud": "South Korea",
    "koweït": "Kuwait",
    "kirghizistan": "Kyrgyzstan",
    "laos": "Laos",
    "lettonie": "Latvia",
    "liban": "Lebanon",
    "lesotho": "Lesotho",
    "liberia": "Liberia",
    "libye": "Libya",
    "liechtenstein": "Liechtenstein",
    "lituanie": "Lithuania",
    "luxembourg": "Luxembourg",
    "macédoine": "Macedonia",
    "madagascar": "Madagascar",
    "malawi": "Malawi",
    "malaisie": "Malaysia",
    "maldives": "Maldives",
    "mali": "Mali",
    "malte": "Malta",
    "îles marshall": "Marshall Islands",
    "mauritanie": "Mauritania",
    "maurice": "Mauritius",
    "mexique": "Mexico",
    "micronésie": "Micronesia",
    "moldavie": "Moldova",
    "monaco": "Monaco",
    "mongolie": "Mongolia",
    "monténégro": "Montenegro",
    "maroc": "Morocco",
    "mozambique": "Mozambique",
    "myanmar": "Myanmar",
    "namibie": "Namibia",
    "nauru": "Nauru",
    "népal": "Nepal",
    "pays-bas": "Netherlands",
    "nouvelle-zélande": "New Zealand",
    "nicaragua": "Nicaragua",
    "niger": "Niger",
    "nigeria": "Nigeria",
    "norvège": "Norway",
    "oman": "Oman",
    "pakistan": "Pakistan",
    "palau": "Palau",
    "palestine": "Palestine",
    "panama": "Panama",
    "papouasie-nouvelle-guinée": "Papua New Guinea",
    "paraguay": "Paraguay",
    "pérou": "Peru",
    "perou": "Peru",
    "philippines": "Philippines",
    "pologne": "Poland",
    "portugal": "Portugal",
    "qatar": "Qatar",
    "roumanie": "Romania",
    "russie": "Russia",
    "rwanda": "Rwanda",
    "saint-kitts-et-nevis": "Saint Kitts and Nevis",
    "sainte-lucie": "Saint Lucia",
    "saint-vincent-et-les-grenadines": "Saint Vincent and the Grenadines",
    "samoa": "Samoa",
    "san-marino": "San Marino",
    "são tomé-et-principe": "Sao Tome and Principe",
    "arabie saoudite": "Saudi Arabia",
    "sénégal": "Senegal",
    "serbie": "Serbia",
    "seychelles": "Seychelles",
    "sierra leone": "Sierra Leone",
    "singapour": "Singapore",
    "slovaquie": "Slovakia",
    "slovénie": "Slovenia",
    "îles salomon": "Solomon Islands",
    "somalie": "Somalia",
    "afrique du sud": "South Africa",
    "soudan du sud": "South Sudan",
    "espagne": "Spain",
    "sri lanka": "Sri Lanka",
    "soudan": "Sudan",
    "suriname": "Suriname",
    "swaziland": "Swaziland",
    "suède": "Sweden",
    "suisse": "Switzerland",
    "syrie": "Syria",
    "taiwan": "Taiwan",
    "tadjikistan": "Tajikistan",
    "tanzanie": "Tanzania",
    "thaïlande": "Thailand",
    "timor-leste": "Timor-Leste",
    "togo": "Togo",
    "tonga": "Tonga",
    "trinité-et-tobago": "Trinidad and Tobago",
    "tunisie": "Tunisia",
    "turquie": "Turkey",
    "turkménistan": "Turkmenistan",
    "tuvalu": "Tuvalu",
    "ouganda": "Uganda",
    "ukraine": "Ukraine",
    "émirats arabes unis": "United Arab Emirates",
    "royaume-uni": "United Kingdom",
    "états-unis": "United States",
    "usa":"United States",
    "uruguay": "Uruguay",
    "ouzbékistan": "Uzbekistan",
    "vanuatu": "Vanuatu",
    "vatican": "Vatican City",
    "venezuela": "Venezuela",
    "vietnam": "Vietnam",
    "yémen": "Yemen",
    "zambie": "Zambia",
    "zimbabwe": "Zimbabwe",
}

def extract_country(text):
    for common_word in country_fr_to_en:
        common_word = common_word.lower()  # Lowercase common_word
        if text is not None:  # Check if product.origine has a value
            text = text.lower()  # Lowercase text only if product.origine is not None
            matches = re.findall(r"\b{}\b".format(common_word), text)
            if matches:
                return matches[0]
        else:
            return ""

# text = "Produit élaboré en France à partir de riz basmati origine non-UE (Inde et/ou Pakistan)"
# country = extract_country(text)
# print(f"Extracted country: {country}")

def extract_all_countries(text):
  """
  Fonction récursive pour extraire tous les noms de pays d'un texte.

  Args:
    text: Le texte à analyser.

  Returns:
    Une liste contenant tous les noms de pays trouvés dans le texte.
  """
  countries = []
  while True:
    text = text.lower()
    country = extract_country(text)
    print("country dans la boucle while :" , country)
    if country is None:
      break
    countries.append(country)
    # Supprimer le pays extrait du texte pour éviter les doublons
    text = text.replace(country, '')
    print("text",text)


  return countries

# text = "Produit élaboré en France à partir de riz basmati origine non-UE (Inde et/ou Pakistan)"
# countries = extract_all_countries(text)

# print(countries)
